Traceback (most recent call last):
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/foss4g/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
catalogue="https://object-store.cloud.muni.cz/swift/v1/foss4g-catalogue/c_gls_NDVI-LTS_1999-2019.json"
LTS = xr.open_mfdataset(
    "reference://", engine="zarr",
    backend_kwargs={
        "storage_options": {
            "fo":catalogue
                    },
        "consolidated": False
    }
)
LTS
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m catalogue[38;5;241m=[39m[38;5;124m"[39m[38;5;124mhttps://object-store.cloud.muni.cz/swift/v1/foss4g-catalogue/c_gls_NDVI-LTS_1999-2019.json[39m[38;5;124m"[39m
[0;32m----> 2[0m LTS [38;5;241m=[39m [43mxr[49m[38;5;241m.[39mopen_mfdataset(
[1;32m      3[0m     [38;5;124m"[39m[38;5;124mreference://[39m[38;5;124m"[39m, engine[38;5;241m=[39m[38;5;124m"[39m[38;5;124mzarr[39m[38;5;124m"[39m,
[1;32m      4[0m     backend_kwargs[38;5;241m=[39m{
[1;32m      5[0m         [38;5;124m"[39m[38;5;124mstorage_options[39m[38;5;124m"[39m: {
[1;32m      6[0m             [38;5;124m"[39m[38;5;124mfo[39m[38;5;124m"[39m:catalogue
[1;32m      7[0m                     },
[1;32m      8[0m         [38;5;124m"[39m[38;5;124mconsolidated[39m[38;5;124m"[39m: [38;5;28;01mFalse[39;00m
[1;32m      9[0m     }
[1;32m     10[0m )
[1;32m     11[0m LTS

[0;31mNameError[0m: name 'xr' is not defined
NameError: name 'xr' is not defined

